# Living room lights
- alias: Living room lights - on in the evening (weekdays)
  trigger:
  - platform: time
    at: '17:30'
  - platform: sun
    event: sunset
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '17:30'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: sun
      after: sunset
  action:
  - service: scene.turn_on
    entity_id: scene.warm

- alias: Living room lights - on in the evening (weekend)
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:45:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: scene.turn_on
    entity_id: scene.warm

- alias: Living room lights - dim while playing video
  hide_entity: false
  trigger:
  - platform: state
    entity_id: media_player.living_room_kodi
    to: 'playing'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.lamp
      state: 'on'
    - condition: template
      value_template: "{{ states.media_player.living_room_kodi.attributes.media_content_type == 'movie' }}"
  action:
  - service: scene.turn_on
    entity_id: scene.movie

- alias: Living room lights - brighten when media stopped/paused
  hide_entity: false
  trigger:
  - platform: state
    entity_id: media_player.living_room_kodi
    from: 'playing'
  condition:
  - condition: state
    entity_id: light.lamp
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.warm

# If the TV LEDs are on when manually powered on but the sun is still up, turn the LEDs off.
# This is required because the LEDs remember their previous state when manually power cycled.
# Delay is because the LEDs do not respond to commands immediately
- alias: TV LEDs - set state off
  hide_entity: true
  trigger:
  - platform: state
    entity_id: light.tv_leds
    from: 'unavailable'
    for:
      seconds: 10
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.tv_leds
      state: 'on'
    - condition: sun
      before: sunset
  action:
  - service: light.turn_off
    entity_id: light.tv_leds

# If the TV LEDs are off when manually powered on but it is after sunset, turn the LEDs on.
# Delay is because the LEDs do not respond to commands immediately
- alias: TV LEDs - set state on
  hide_entity: true
  trigger:
  - platform: state
    entity_id: light.tv_leds
    from: 'unavailable'
    for:
      seconds: 10
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.tv_leds
      state: 'off'
    - condition: sun
      after: sunset
  action:
  - service: scene.turn_on
    entity_id: scene.warm