- platform: bayesian
  prior: 0.7 # Probability that I'm home
  name: 'Bayesian Presence'
  observations:
    - entity_id: 'device_tracker.ross_phone'
      prob_given_true: 0.9
      platform: 'state'
      to_state: 'home'
    - entity_id: 'binary_sensor.ross_keys'
      prob_given_true: 0.3
      platform: 'state'
      to_state: 'off'

- platform: mqtt
  name: "Living room PIR"
  state_topic: "/mqtt-gpio-monitor/out/11"
  qos: 0
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy

- platform: mqtt
  name: "Study PIR"
  state_topic: "/mqtt-gpio-monitor/out/12"
  qos: 0
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy

- platform: mqtt
  name: "Kitchen PIR"
  state_topic: "/mqtt-gpio-monitor/out/13"
  qos: 0
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy

- platform: mqtt
  name: "Bedroom PIR"
  state_topic: "/mqtt-gpio-monitor/out/15"
  qos: 0
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy

- platform: mqtt
  name: "Front door"
  state_topic: "/mqtt-gpio-monitor/out/16"
  qos: 0
  payload_on: "1"
  payload_off: "0"
  device_class: opening

- platform: mqtt
  name: "Ross keys"
  state_topic: "ibeacon/00001803-494c-4f47-4943-544543480000"
  qos: 0
  payload_on: "1"
  payload_off: "0"
  device_class: presence

- platform: command_line
  name: Raspberry Pi
  command: ping -W 1 -c 1 192.168.0.151 > /dev/null 2>&1 && echo online || echo offline
  device_class: connectivity
  payload_on: "online"
  payload_off: "offline"
