- platform: time_date
  display_options:
  - 'time'
  - 'date'

- platform: google_travel_time
  name: Ross travel time
  api_key: !secret google_travel_time_api_key
  origin: device_tracker.ross_phone
  destination: zone.Home
  options:
    units: imperial

- platform: nest

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
  - 'temperature'
  - 'apparent_temperature'
  - 'temperature_max'
  - 'temperature_min'
  - 'wind_speed'
  - 'cloud_cover'
  - 'humidity'
  - 'precip_probability'
  - 'precip_type'

- platform: metoffice
  api_key: !secret metoffice_api_key
  monitored_conditions:
  - weather
  - temperature
  - feels_like_temperature
  - wind_speed
  - wind_direction
  - uv
  - precipitation
  - humidity

- platform: season
  type: meteorological

- platform: uptime

- platform: template
  sensors: 
    distance_from_home:
      value_template: '{{ states.sensor.ross_travel_time.attributes.distance }}'
      friendly_name: 'Distance away'
      icon_template: 'mdi:ruler'

    heating_mode:
      value_template: '{{ states.climate.living_room.attributes.operation_mode }}'
      friendly_name: 'Heating mode'
      icon_template: 'mdi:thermostat'

    nest_away_mode:
      value_template: '{{ states.climate.living_room.attributes.away_mode }}'
      friendly_name: 'Away mode'
      icon_template: >
        {%- if states.climate.living_room.attributes.away_mode == "on" -%}
        mdi:home-outline
        {%- else -%}
        mdi:home-account
        {%- endif -%}
    
    smoke_detector:
      value_template: >
        {%- if states.binary_sensor.hallway_nest_protect_online.state == "on" -%}
        Online
        {%- else -%}
        Offline
        {%- endif -%}
      friendly_name: Smoke/CO² detector
      icon_template: >
        {%- if states.binary_sensor.hallway_nest_protect_online.state == "on" -%}
        mdi:smoke-detector
        {%- else -%}
        mdi:alert-circle-outline
        {%- endif -%}

    # Lights
    outside_light:
      value_template: '{{ states.light.outside.state }}'
      friendly_name: 'Outside light'
      icon_template: >
        {%- if states.light.outside.state == "on" -%}
        mdi:lightbulb-on
        {%- else -%}
        mdi:lightbulb-outline
        {%- endif -%}

    stairwell_lights:
      value_template: '{{ states.light.stairwell.state }}'
      friendly_name: 'Stairwell lights'
      icon_template: >
        {%- if states.light.stairwell.state == "on" -%}
        mdi:lightbulb-on
        {%- else -%}
        mdi:lightbulb-outline
        {%- endif -%}

    living_room_lights:
      value_template: '{{ states.group.living_room_lights.state }}'
      friendly_name: 'Living room lights'
      icon_template: >
        {%- if states.group.living_room_lights.state == "on" -%}
        mdi:lightbulb-on
        {%- else -%}
        mdi:lightbulb-outline
        {%- endif -%}

    living_room_chromecast:
      value_template: '{{ states.media_player.living_room_chromecast.state }}'
      friendly_name: 'Living room Chromecast'
      icon_template: 'mdi:google-chrome'

    living_room_kodi:
      value_template: '{{ states.media_player.living_room_kodi.state }}'
      friendly_name: 'Living room Kodi'
      icon_template: 'mdi:kodi'

    bedroom_kodi:
      value_template: '{{ states.media_player.bedroom_kodi.state }}'
      friendly_name: 'Bedroom Kodi'
      icon_template: 'mdi:kodi'

    raspberry_pi:
      value_template: >
        {%- if states.binary_sensor.raspberry_pi.state == "on" -%}
        Online
        {%- else -%}
        Offline
        {%- endif -%}
      friendly_name: 'Raspberry Pi'
      icon_template: >
        {%- if states.binary_sensor.raspberry_pi.state == "on" -%}
        mdi:raspberrypi
        {%- else -%}
        mdi:alert-circle-outline
        {%- endif -%}

    # Room occupancy
    study_pir:
      value_template: >
        {%- if states.input_boolean.study_pir.state == "on" -%}
        Occupied
        {%- else -%}
        Unoccupied
        {%- endif -%}
      friendly_name: 'Study'
      icon_template: >
        {%- if states.input_boolean.study_pir.state == "on" -%}
        mdi:check-circle
        {%- else -%}
        mdi:checkbox-blank-circle-outline
        {%- endif -%}

    living_room_pir:
      value_template: >
        {% if states.input_boolean.living_room_pir.state == "on" -%}
        Occupied
        {%- else -%}
        Unoccupied
        {%- endif -%}
      friendly_name: 'Living room'
      icon_template: >
        {%- if states.input_boolean.living_room_pir.state == "on" -%}
        mdi:check-circle
        {%- else -%}
        mdi:checkbox-blank-circle-outline
        {%- endif -%}

    kitchen_pir:
      value_template: >
        {%- if states.input_boolean.kitchen_pir.state == "on" -%}
        Occupied
        {%- else -%}
        Unoccupied
        {%- endif -%}
      friendly_name: 'Kitchen'
      icon_template: >
        {%- if states.input_boolean.kitchen_pir.state == "on" -%}
        mdi:check-circle
        {%- else -%}
        mdi:checkbox-blank-circle-outline
        {%- endif -%}

    bedroom_pir:
      value_template: >
        {%- if states.input_boolean.bedroom_pir.state == "on" -%}
        Occupied
        {%- else -%}
        Unoccupied
        {%- endif -%}
      friendly_name: 'Bedroom'
      icon_template: >
        {%- if states.input_boolean.bedroom_pir.state == "on" -%}
        mdi:check-circle
        {%- else -%}
        mdi:checkbox-blank-circle-outline
        {%- endif -%}

    front_door:
      value_template: >
        {%- if states.binary_sensor.front_door.state == "on" %}
        Open
        {%- else -%}
        Closed
        {%- endif -%}
      friendly_name: 'Front door'
      icon_template: >
        {%- if states.binary_sensor.front_door.state == "on" %}
        mdi:checkbox-blank-outline
        {%- else -%}
        mdi:checkbox-marked
        {%- endif -%}

    # Washing machine logic
    washing_machine_state:
      friendly_name: State
      value_template: >
        {% if (states.switch.washing_machine_mains.attributes.current_power_w | float > 0.2) and (states.switch.washing_machine_mains.attributes.current_power_w | float < 3.0) %}
        idle
        {% elif (states.switch.washing_machine_mains.attributes.current_power_w | float > 3.0) and (states.switch.washing_machine_mains.attributes.current_power_w | float < 200.0) %}
        running
        {% elif (states.switch.washing_machine_mains.attributes.current_power_w | float > 200.0) and (states.switch.washing_machine_mains.attributes.current_power_w | float < 1550.0) %}
        drying
        {% elif (states.switch.washing_machine_mains.attributes.current_power_w | float > 1550.0) and (states.switch.washing_machine_mains.attributes.current_power_w | float < 2100.0) %}
        washing
        {% else %}
        off
        {% endif %}

    # The following washing machine sensors are only used to display data on the front end
    washing_machine:
      friendly_name: Washing machine state
      value_template: '{{ states.input_select.washing_machine_status.state }}'
      icon_template: mdi:washing-machine

    washing_machine_current_power:
      friendly_name: Current power draw
      unit_of_measurement: W
      value_template: '{{ states.switch.washing_machine_mains.attributes.current_power_w | round(0) }}'
      icon_template: mdi:gauge      
 
    washing_machine_today_power:
      friendly_name: Todays power consumption
      unit_of_measurement: kWh
      value_template: '{{ states.switch.washing_machine_mains.attributes.today_energy_kwh | round(1) }}'
      icon_template: mdi:gauge

    washing_machine_total_power:
      friendly_name: Total power consumption
      unit_of_measurement: kWh
      value_template: '{{ states.switch.washing_machine_mains.attributes.total_energy_kwh | round(1) }}'
      icon_template: mdi:gauge