# Turn the heating up if it's cold outside in the evening
- alias: Heating - warmer in the evening if it's cold outside
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: 7
  condition:
    condition: and
    conditions:
    - condition: time
      after: '21:30'
      before: '23:59'
    - condition: template
      value_template: "{{ states.climate.living_room.attributes.operation_mode == 'heat' }}"
    - condition: template
      value_template: "{{ states.climate.living_room.attributes.temperature < 22 }}"
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
      temperature: 22


- alias: Heating - raise temp weekend when I get up
  initial_state: false
  trigger:
  - platform: state
    entity_id: sensor.kitchen_pir
    to: 'Occupied'
  condition:
  - condition: template
    value_template: "{{ states.climate.living_room.attributes.temperature < 20 }}"
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
      temperature: 20
  - service: automation.turn_off
    entity_id: automation.heating__raise_temp_weekend_when_i_get_up

- alias: Heating - extended away
  trigger:
  - platform: state
    entity_id: group.tracker_ross
    from: 'Home'
    to: 'Away'
    for:
      hours: 16
  condition:
  - condition: template
    value_template: '{{ states.climate.living_room.attributes.operation_mode == "eco" }}'
  action:
  - service: climate.set_operation_mode
    entity_id: climate.living_room
    data:
      temperature: 10