# On periods
- alias: Heating - on weekday mornings
  trigger:
  - platform: time
    at: '6:15'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: group.tracker_ross
      state: 'home'
    - condition: template
      value_template: '{{ states.climate.living_room.attributes.operation_mode == "heat" }}'
  action:
  - service: climate.set_operation_mode
    entity_id: climate.living_room
    data:
      operation_mode: heat
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
      temperature: 18
  - service: notify.telegram
    data:
      message: "Heating has been set to 18°C."

- alias: Heating - on weekend mornings
  trigger:
  - platform: time
    at: '8:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - sat
      - sun
    - condition: template
      value_template: '{{ states.climate.living_room.attributes.operation_mode == "heat" }}'      
    - condition: state
      entity_id: group.tracker_ross
      state: 'home'
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
      temperature: 18
  - service: automation.turn_on
    entity_id: automation.heating__raise_temp_weekend_when_i_get_up

- alias: Heating - on in the evening
  trigger:
  - platform: time
    at: '16:45'
  - platform: numeric_state
    entity_id: sensor.ross_travel_time
    below: 45
  condition:
    condition: and
    conditions:
    - condition: time
      after: '16:45'
      before: '18:30'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: template
      value_template: "{{ states.climate.living_room.attributes.operation_mode == 'eco' }}"
    - condition: numeric_state
      entity_id: sensor.ross_travel_time
      below: 45
  action:
  - service: climate.set_operation_mode
    entity_id: climate.living_room
    data:
      operation_mode: heat
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
      temperature: 20
  - service: notify.telegram
    data:
      message: "Heating has been set to 20°C."