# Because the PIRs are only activated momentarily, we use the following automations to switch on an input boolean and then again
# to switch them off but with a delay.
- alias: Study occupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.study_pir
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.study_pir

- alias: Study unoccupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.study_pir
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.study_pir

- alias: Living room occupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.living_room_pir
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.living_room_pir

- alias: Living room unoccupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.living_room_pir
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.living_room_pir

- alias: Kitchen occupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.kitchen_pir
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.kitchen_pir

- alias: Kitchen unoccupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.kitchen_pir
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.kitchen_pir

- alias: Bedroom occupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.bedroom_pir
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.bedroom_pir

- alias: Bedroom unoccupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.bedroom_pir
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedroom_pir