- alias: Security - Notify of activity if in away mode
  trigger: 
  - platform: state
    entity_id: sensor.bedroom_pir, sensor.kitchen_pir, sensor.living_room_pir, sensor.study_pir  
    to: 'Occupied'
  condition:
  - condition: state
    entity_id: sensor.tracker_ross
    state: 'Away'
  action:
  - service: notify.telegram
    data_template:
      message: >
        {% if states.sensor.bedroom_pir.state == "Occupied" %}
        Activity detected in the bedroom!
        {% elif states.sensor.kitchen_pir.state == "Occupied" %}
        Activity detected in the kitched!
        {% elif states.sensor.living_room_pir.state == "Occupied" %}
        Activity detected in the living room!
        {% elif states.sensor.study_pir.state == "Occupied" %}
        Activity detected in the study!
        {% else %}
        Activity detected at home!
        {% endif %}