- alias: Home Assistant - update notifications
  hide_entity: true
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
    service: notify.telegram
    data:
      message: 'There is a new Home Assistant release available.'

- alias: Disable all automations
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_boolean.kill_switch
    to: 'on'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: group.all_automations
  - service: homeassistant.turn_on
    data:
      entity_id: automation.enable_all_automations

- alias: Enable all automations
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_boolean.kill_switch
    to: 'off'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: group.all_automations