- alias: Home Assistant - update notifications
  hide_entity: true
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
    service: notify.telegram
    data:
      message: 'There is a new Home Assistant release available.'

- alias: Refresh Raspberry PI MQTT topics
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data_template:
      topic: "/mqtt-gpio-monitor/refresh"
      payload: "1"