# Outside light
- alias: Lights - outside on at sunset
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: light.turn_on
    data:
      entity_id: light.outside
      brightness: 254

- alias: Lights - outside off at sunrise
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    data:
      entity_id: light.outside

# Stairwell lights. Entity called is a Hue room.
- alias: Lights - stairwell on in the evening
  trigger:
  - platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
  - service: light.turn_on
    data:
      entity_id: light.stairwell
      brightness: 128

- alias: Lights - stairwell off in the morning
  trigger:
  - platform: sun
    event: sunrise
    offset: '00:30:00'
  action:
  - service: light.turn_off
    data:
      entity_id: light.stairwell

# Living room lights
- alias: Living room lights - on in the evening
  trigger:
  - platform: time
    at: '17:30'
  - platform: sun
    event: sunset
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '17:30'
    - condition: sun
      after: sunset
  action:
  - service: scene.turn_on
    entity_id: scene.warm

- alias: Living room lights - dim while playing video
  hide_entity: false
  trigger:
  - platform: state
    entity_id: media_player.living_room_kodi
    to: 'playing'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.lamp
      state: 'on'
    - condition: template
      value_template: "{{ states.media_player.living_room_kodi.attributes.media_content_type == 'movie' }}"
  action:
  - service: scene.turn_on
    entity_id: scene.movie

- alias: Living room lights - brighten when media stopped/paused
  hide_entity: false
  trigger:
  - platform: state
    entity_id: media_player.living_room_kodi
    from: 'playing'
  condition:
  - condition: state
    entity_id: light.lamp
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.warm

# If the TV LEDs are on when manually powered on but the sun is still up, turn the LEDs off.
# This is required because the LEDs remember their previous state when manually power cycled.
#- alias: TV LEDs - set state off
#  hide_entity: true
#  trigger:
#  - platform: state
#    entity_id: light.tv_leds
#    to: 'on'
#  condition:
#  - condition: sun
#    before: sunset
#  action:
#  - service: light.turn_off
#    entity_id: light.tv_leds

# If the TV LEDs are off when manually powered on but it is after sunset, turn the LEDs on.
#- alias: TV LEDs - set state on
#  hide_entity: true
#  trigger:
#  - platform: state
#    entity_id: light.tv_leds
#    to: 'on'
#  condition:
#  - condition: sun
#    after: sunset
#  action:
#  - service: light.turn_on
#    entity_id: light.tv_leds

# Study desk LEDs
- alias: Lights - Computer desk LEDs on
  trigger:
  - platform: state
    entity_id: light.computer_desk_leds
    from: 'unavailable'
  - platform: state
    entity_id: sensor.study_pir
    to: 'occupied'
  - platform: sun
    event: sunset
    offset: '-2:00:00'
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
      after_offset: '-2:00:00'
    - condition: state
      entity_id: sensor.study_pir
      state: 'occupied'
  action:
  - service: light.turn_on
    entity_id: light.computer_desk_leds

- alias: Lights - Computer desk LEDs off
  trigger:
  - platform: state
    entity_id: sensor.study_pir
    to: 'unoccupied'
  condition:
  - condition: state
    entity_id: light.computer_desk_leds
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.computer_desk_leds
