# The condition below ensures that the system is in eco mode before switching to heat.
# This avoids switching the system to heat when it has been manually set to off (and if already heat, do nothing).
- alias: Heating - switch to heat when home
  trigger:
  - platform: state
    entity_id: group.tracker_ross
    to: 'home'
  condition:
  - condition: template
    value_template: '{{ states.climate.living_room.attributes.operation_mode == "eco" }}'
  action:
  - service: climate.set_away_mode
    entity_id: climate.living_room
    data:
      away_mode: false  
  - service: climate.set_operation_mode
    entity_id: climate.living_room
    data:
      operation_mode: heat

# The condition below ensures that the system is in heat mode before switching to eco.
# This avoids switching the system to eco when it has been manually set to off (and if already eco, do nothing).
- alias: Heating - switch to eco when away
  trigger:
  - platform: state
    entity_id: group.tracker_ross
    to: 'not_home'
    for:
      minutes: 5
  condition:
  - condition: template
    value_template: '{{ states.climate.living_room.attributes.operation_mode == "heat" }}'
  action:
  - service: climate.set_away_mode
    entity_id: climate.living_room
    data:
      away_mode: true  
  - service: climate.set_operation_mode
    entity_id: climate.living_room
    data:
      operation_mode: eco