# The Nest home/away mode does not change the operation mode (heat, eco, off). Separate automation for this below.
- alias: Nest - home mode when home
  trigger:
  - platform: state
    entity_id: sensor.tracker_ross
    from: 'Away'
    to: 'Home'
  action:
  - service: climate.set_away_mode
    entity_id: climate.living_room
    data:
      away_mode: false

# The condition below ensures that the system is in eco mode before switching to heat.
# This avoids switching the system to heat when it has been manually set to off (and if already heat, do nothing).
- alias: Heating - switch to heat when home
  trigger:
  - platform: state
    entity_id: sensor.tracker_ross
    from: 'Away'
    to: 'Home'
    for:
      minutes: 1
  condition:
  - condition: template
    value_template: '{{ states.climate.living_room.attributes.operation_mode == "eco" }}'
  action:
  - service: climate.set_operation_mode
    entity_id: climate.living_room
    data:
      operation_mode: heat

# The Nest home/away mode does not change the operation mode (heat, eco, off). Separate automation for this below.
- alias: Nest - away mode when out
  trigger:
  - platform: state
    entity_id: sensor.tracker_ross
    from: 'Home'
    to: 'Away'
    for:
      minutes: 3
  action:
  - service: climate.set_away_mode
    entity_id: climate.living_room
    data:
      away_mode: true

# The condition below ensures that the system is in heat mode before switching to eco.
# This avoids switching the system to eco when it has been manually set to off (and if already eco, do nothing).
- alias: Heating - switch to eco when away
  trigger:
  - platform: state
    entity_id: sensor.tracker_ross
    from: 'Home'
    to: 'Away'
    for:
      minutes: 3
  condition:
  - condition: template
    value_template: '{{ states.climate.living_room.attributes.operation_mode == "heat" }}'
  action:
  - service: climate.set_operation_mode
    entity_id: climate.living_room
    data:
      operation_mode: eco