# This automation will send a message to Telegram if any of the PIRs are activated while HA is in Away Mode. To limit 
# notification spam (usually caused by HA not seeing my phone) the automation turns itself off, sends the Telegram message, waits
# 2 minutes then finally, turns the automation back on.
- alias: Security - Notify of activity if in away mode
  trigger: 
  - platform: state
    entity_id: binary_sensor.study_pir
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_pir
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_pir
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bedroom_pir
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: device_tracker.ross_oneplusx
    state: 'not_home'
  action:
  - service: automation.turn_off
    entity_id: automation.security__notify_of_activity_if_in_away_mode
  - service: notify.telegram
    data:
      message: "Activity detected at home"
  - delay:
      minutes: 2
  - service: automation.turn_on
    entity_id: automation.security__notify_of_activity_if_in_away_mode  

# Because the PIRs are only activated momentarily, we use the following automations to switch on an input boolean and then again
# to switch them off but with a delay.
- alias: Study occupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.study_pir
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.study_pir

- alias: Study unoccupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.study_pir
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.study_pir

- alias: Living room occupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.living_room_pir
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.living_room_pir

- alias: Living room unoccupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.living_room_pir
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.living_room_pir

- alias: Kitchen occupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.kitchen_pir
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.kitchen_pir

- alias: Kitchen unoccupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.kitchen_pir
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.kitchen_pir

- alias: Bedroom occupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.bedroom_pir
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.bedroom_pir

- alias: Bedroom unoccupied
  hide_entity: true
  trigger: 
  - platform: state
    entity_id: binary_sensor.bedroom_pir
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedroom_pir