- alias: Bedtime
  trigger:
  - platform: time
    at: '23:30'    
  - platform: state
    entity_id: sensor.living_room_pir, sensor.study_pir
    to: 'Unoccupied'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '23:30'
      before: '06:00'
    - condition: state
      entity_id: sensor.living_room_pir
      state: 'Unoccupied'
    - condition: state
      entity_id: sensor.study_pir
      state: 'Unoccupied'
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
      temperature: 15
  - service: light.turn_off
    data:
      entity_id: light.lamp
  - service: light.turn_off
    data:
      entity_id: light.tv_leds
  - service: notify.all_kodi
    data:
      title: "Home Assistant"
      message: "Lights off and heating set to low"
      data:
        displaytime: 3500
  - service: automation.turn_off
    entity_id: automation.bedtime

- alias: Daytime
  trigger:
  - platform: state 
    entity_id: sensor.kitchen_pir
    to: 'Occupied'
  condition: 
  - condition: state
    entity_id: automation.bedtime
    state: 'off'
  action:
  - service: automation.turn_on
    entity_id: automation.bedtime