- alias: Night mode
  trigger:
  - platform: time
    at: '23:30'    
  - platform: state
    entity_id: sensor.living_room_pir
    to: 'unoccupied'
  - platform: state
    entity_id: sensor.study_room_pir
    to: 'unoccupied'    
  condition:
    condition: and
    conditions:
    - condition: time
      after: '23:30'
      before: '06:00'
    - condition: state
      entity_id: input_boolean.daynight_mode
      state: 'off'
    - condition: state
      entity_id: sensor.living_room_pir
      state: 'unoccupied'
    - condition: state
      entity_id: sensor.study_pir
      state: 'unoccupied'
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
      temperature: 15 ## This needs work. Will set to 15 even if in eco mode (13)
  - service: light.turn_off
    data:
      entity_id: light.lamp
  - service: light.turn_off
    data:
      entity_id: light.tv_leds
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.daynight_mode
  - service: notify.all_kodi
    data:
      title: "Home Assistant"
      message: "Lights off and heating set to low"

- alias: Day mode
  trigger:
  - platform: state
    entity_id: sensor.kitchen_pir
    to: 'occupied'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '06:00'
    - condition: state
      entity_id: input_boolean.daynight_mode
      state: 'on'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.daynight_mode